# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

orbs:
  prebuild-orb: netgaintechnology/prebuild-orb@volatile
  orb-tools: circleci/orb-tools@volatile

executors:
  node:
    docker:
      - image: circleci/node:latest
    resource_class: small

version: 2.1
jobs:
  build:
    executor: node

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  workflow:
    jobs:
      - prebuild-orb/yaml_lint
