version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
    resource_class: small
  ios:
    macos:
      xcode: 11.1.0
    resource_class: small

jobs:
  build:
    executor: node
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hello world"
  ios-build:
    executor: ios
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  workflow:
    jobs:
      - build
