version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
    resource_class: small

  ios:
    macos:
      xcode: 11.1.0
    resource_class: small

  android:
    working_directory: ~/AwesomeProject/android
    docker:
      - image: circleci/android:api-27-node8-alpha

    dependencies:
       cache_directories: '/opt/circleci/.rvm/gems'
       pre: gem install fastlane

    steps:
      - checkout:
          path: ~/AwesomeProject

      - run:
          name: install dependency
          command: |
            gem update --system
            gem install bundler

      - restore_cache:
          key: 1-gems-{{ checksum \"Gemfile.lock\" }}

      - run: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: 1-gems-{{ checksum \"Gemfile.lock\" }}
          paths:
            - vendor/bundle

      - run: export PATH=\"$HOME/.fastlane/bin:$PATH\"

      - run: bundle exec fastlane add_plugin appcenter

      - save_cache:
          key: bundle-v1-{{ checksum \"Gemfile.lock\" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run: ls

      - run:
          name: fastlane beta
          command: bundle exec fastlane beta
jobs:
  build:
    executor: node
    working_directory: ~/repo
    dependencies:
       cache_directories: '/opt/circleci/.rvm/gems'
       pre: gem install fastlane
    steps:
      - checkout
      - run: echo "hello world"
  ios-build:
    executor: ios
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - android
