# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:latest
    resource_class: small

jobs:
  build:
    executor: node

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  workflow:
    jobs:
      - build
